# Generated by Django 2.1.2 on 2018-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='zip',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
