# Generated by Django 2.1.2 on 2018-10-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0003_family_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='city',
            field=models.CharField(choices=[('Foley', 'Foley'), ('Foreston', 'Foreston'), ('Gilman', 'Gilman')], max_length=50),
        ),
    ]
