# Generated by Django 2.1.2 on 2018-10-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0004_auto_20181004_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='family',
            name='child_support',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='fuel_assist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='general_assist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='insurance_assistance',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Assistance', 'Assistance')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='mfip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='monthly_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='pension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='proof_of_address',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='social_security',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='ssi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='unemployment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='wages1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='wages2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='wic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='workers_comp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='city',
            field=models.CharField(choices=[('Foley', 'Foley'), ('Foreston', 'Foreston'), ('Gilman', 'Gilman'), ('Milaca', 'Milaca'), ('Oak', 'Oak'), ('Park', 'Park'), ('Princeton', 'Princeton'), ('Rice', 'Rice'), ('Royalton', 'Royalton'), ('Sartell', 'Sartell'), ('Sauk Rapids', 'Sauk Rapids'), ('St Cloud', 'St Cloud')], max_length=50),
        ),
    ]
