# Generated by Django 2.1.2 on 2018-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0006_auto_20181005_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='race',
            field=models.CharField(choices=[('W', 'W'), ('B', 'B'), ('A', 'A'), ('H', 'H'), ('N', 'N'), ('P', 'P'), ('T', 'T'), ('O', 'O')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], max_length=140),
        ),
    ]
