# Generated by Django 2.1.2 on 2018-10-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0006_auto_20181005_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='primary_contact_last_name',
        ),
        migrations.AddField(
            model_name='family',
            name='primary_contact_first_name',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='race',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Black or African American'), ('NA', 'Native American or Alaska Native'), ('A', 'Asian'), ('NH', 'Native Hawaiian or Other Pacific Islander'), ('H', 'Hispanic, Latino or Spanish Origin'), ('T', 'Two or More Races'), ('O', 'Other Race')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], max_length=140),
        ),
    ]
