# Generated by Django 2.1.2 on 2018-10-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0007_auto_20181021_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pounds_of_food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visit_notes', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyRecords.Family')),
            ],
        ),
    ]
