# Generated by Django 2.1.2 on 2018-10-24 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0009_auto_20181023_2240'),
        ('familyRecords', '0007_auto_20181023_1212'),
    ]

    operations = [
    ]
