# Generated by Django 2.1.2 on 2018-11-16 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0010_merge_20181023_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='child_support',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='city',
            field=models.CharField(choices=[('Foley', 'Foley'), ('Foreston', 'Foreston'), ('Gilman', 'Gilman'), ('Milaca', 'Milaca'), ('Oak Park', 'Oak Park'), ('Princeton', 'Princeton'), ('Rice', 'Rice'), ('Royalton', 'Royalton'), ('Sartell', 'Sartell'), ('Sauk Rapids', 'Sauk Rapids'), ('St Cloud', 'St Cloud')], max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 11, 15)),
        ),
        migrations.AlterField(
            model_name='family',
            name='fuel_assist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='general_assist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='mfip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='monthly_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='notes',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='family',
            name='pension',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='snap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='social_security',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='ssi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='unemployment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='wages1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='wages2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='wic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='workers_comp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 1, 37, 18, 934965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='race',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Black or African American'), ('NA', 'Native American or Alaska Native'), ('A', 'Asian'), ('NH', 'Native Hawaiian or Other Pacific Islander'), ('H', 'Hispanic, Latino or Spanish Origin'), ('T', 'Two or More Races'), ('O', 'Other Race')], max_length=140),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 11, 15)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='total_active_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_notes',
            field=models.TextField(default='NA'),
        ),
    ]
