# Generated by Django 2.1.2 on 2018-11-16 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0011_auto_20181115_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Non-Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 2, 2, 9, 841620, tzinfo=utc)),
        ),
    ]
