# Generated by Django 2.1.2 on 2018-11-16 02:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0012_auto_20181115_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 2, 3, 36, 292584, tzinfo=utc)),
        ),
    ]
