# Generated by Django 2.1.2 on 2018-11-21 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0013_auto_20181115_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 11, 20)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 1, 40, 59, 945694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 11, 20)),
        ),
    ]
