# Generated by Django 2.1.2 on 2018-11-21 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0014_auto_20181120_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 1, 43, 50, 711629, tzinfo=utc)),
        ),
    ]
