# Generated by Django 2.1.2 on 2018-11-21 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0015_auto_20181120_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='volunteer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='volunteer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='volunteer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 21, 2, 4, 12, 322188, tzinfo=utc)),
        ),
    ]
