# Generated by Django 2.1.2 on 2018-12-04 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0017_auto_20181124_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pounds_of_bread', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.date(2018, 12, 4))),
                ('visit_notes', models.TextField(default='NA')),
            ],
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 4)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 4, 22, 40, 14, 117606, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 4)),
        ),
        migrations.AddField(
            model_name='breadvisit',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyRecords.Family'),
        ),
    ]
