# Generated by Django 2.1.2 on 2018-12-08 21:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0018_auto_20181204_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2018, 12, 8))),
                ('project', models.CharField(choices=[('holidayFood1', 'Holiday Food 1'), ('holidayFood2', 'Holiday Food 2'), ('schoolSupplies', 'School Supplies'), ('givingTree', 'Giving Tree'), ('Other', 'Other')], max_length=140)),
                ('project_notes', models.TextField(default='NA')),
                ('volunteer', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='breadvisit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 8)),
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 8)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 21, 45, 9, 999276, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2018, 12, 8)),
        ),
        migrations.AddField(
            model_name='specialproject',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyRecords.Family'),
        ),
    ]
