# Generated by Django 2.2.1 on 2019-05-13 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0021_auto_20181208_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadvisit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 5, 13)),
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 5, 13)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 15, 26, 39, 194998, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 5, 13)),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='project',
            field=models.CharField(choices=[('Holiday Food 1', 'Holiday Food 1'), ('Holiday Food 2', 'Holiday Food 2'), ('School Supplies', 'School Supplies'), ('Giving Tree', 'Giving Tree'), ('Other', 'Other')], max_length=140),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 5, 13)),
        ),
    ]
