# Generated by Django 2.2.1 on 2019-06-17 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0022_auto_20190513_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadvisit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 6, 17)),
        ),
        migrations.AlterField(
            model_name='family',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 6, 17)),
        ),
        migrations.AlterField(
            model_name='family',
            name='volunteer',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 13, 42, 54, 797985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 6, 17)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=datetime.date(2019, 6, 17)),
        ),
    ]
