# Generated by Django 2.2.1 on 2019-06-17 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0023_auto_20190617_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 13, 47, 44, 191159, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='volunteer',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
