# Generated by Django 2.2.1 on 2019-06-17 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('familyRecords', '0024_auto_20190617_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='volunteer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 19, 4, 4, 367892, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Active', max_length=140),
        ),
        migrations.AlterField(
            model_name='person',
            name='volunteer',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='volunteer',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
