# Generated by Django 2.1.2 on 2018-11-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
