# Generated by Django 2.1.1 on 2018-10-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('familyRecords', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pounds_of_food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('visit_notes', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familyRecords.Family')),
            ],
        ),
    ]
