# Generated by Django 2.1.2 on 2018-10-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitRecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='family',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
